name: Git Tag From Semver Increment

on:
  workflow_call:
    inputs:
      semver-increment:
        description: The semver increment that indicates which release version will be produced.
        required: true
        type: string
      skip:
        type: boolean
        description: Whether to skip the workflow or not.
        required: false
        default: false
    secrets:
      github-token:
        description: |
          The GitHub token utilized to push the tags. Defaults to the GITHUB_TOKEN otherwise.
        required: false
    outputs:
      tags:
        description: A JSON array of tags applied to the HEAD commit.
        value: ${{ jobs.git-tag-semver-from-label.outputs.tags }}

permissions:
  contents: write
  pull-requests: write

env:
  status-report-action-repository: infrastructure-blocks/git-tag-from-semver-increment-workflow

jobs:
  git-tag-from-semver-increment:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tags: ${{ steps.git-tag.outputs.tags }}
    steps:
      - if: ${{ !inputs.skip }}
        id: variables
        run: |
          if test "${{ runner.debug }}" = "1"; then
            set -x
          fi
          
          if test -n "${{ secrets.github-token }}"; then
            echo "token=${{ secrets.github-token }}" >> "${GITHUB_OUTPUT}"
          else
            echo "token=${{ github.token }}" >> "${GITHUB_OUTPUT}"
          fi
          
          # Take the head SHA from a pull request event, github.sha otherwise.
          event_pull_request=$(cat "${GITHUB_EVENT_PATH}" | jq '.pull_request' -c)
          if test -n "${event_pull_request}" && test "${event_pull_request}" != "null"; then
            sha=$(echo "${event_pull_request}" | jq -r '.head.sha')
            echo "sha=${sha}" >> ${GITHUB_OUTPUT}
          else
            echo "sha=${GITHUB_SHA}" >> ${GITHUB_OUTPUT}
          fi
      - if: ${{ !inputs.skip }}
        uses: actions/checkout@v4
        with:
          ref: ${{  steps.variables.outputs.sha }}
          token: ${{ steps.variables.outputs.token }}
      - if: ${{ !inputs.skip }}
        id: git-tag
        uses: infrastructure-blocks/git-tag-semver-action@v1
        with:
          version: ${{ inputs.semver-increment }}
      - if: ${{ !inputs.skip }}
        uses: infrastructure-blocks/status-report-action@v1
        with:
          issue-number: ${{ steps.get-current-pr.outputs.number }}
          body: |
            :rocket: **Success**: Commit ${{ steps.variables.outputs.sha }} tagged!
            Tags:
              - [${{ fromJson(steps.git-tag.outputs.tags)[0] }}](https://github.com/${{ github.repository }}/releases/tag/${{ fromJson(steps.git-tag.outputs.tags)[0] }})
              - [${{ fromJson(steps.git-tag.outputs.tags)[1] }}](https://github.com/${{ github.repository }}/releases/tag/${{ fromJson(steps.git-tag.outputs.tags)[1] }})
              - [${{ fromJson(steps.git-tag.outputs.tags)[2] }}](https://github.com/${{ github.repository }}/releases/tag/${{ fromJson(steps.git-tag.outputs.tags)[2] }})
      - if: ${{ failure() && !inputs.skip }}
        uses: infrastructure-blocks/status-report-action@v1
        with:
          issue-number: ${{ steps.get-current-pr.outputs.number }}
          body: |
            :boom: **Error**: Tagging sha ${{ steps.variables.outputs.sha }} with version bump `${{ inputs.semver-increment }}`
